### ISSUE TITLE
Should I Really Need To Setup Sparky Server ?

### ISSUE THREAD

**Issue by ananth10** [coresystemsFSM/android-twilio-video-with-service#4]
Should i really need to setup sparky server to get  twtToken? or Can i use below code  in this project
((https://github.com/coresystemsFSM/android-twilio-video-with-service/tree/master/app/src/main/java/com/coresystems/twiliovideo/view)) to generate jwttoken?

 **final String key = "john.doe@gmail.com";
        final String jwtToken;
            // Create Conversations messaging grant
            ConversationsGrant grant = new ConversationsGrant();
            grant.configurationProfileSid = VIDEO_CONFIGURATION_SID;
            AccessToken token = new AccessToken.Builder(ACCOUNT_SID, API_KEY, API_SECRET)
                    .identity(key)
                    .grant(grant)
                    .build();
            jwtToken = token.toJWT();**

**Comment by FranziscaZarrai** [comment]
@ananth10 The twilio SDK for Android afaik does not provide the same classes as the server-side SDK. At least I didnt find the ConversationsGrant class. But that aside I do not recommend, generating tokens on the clients themselves. For once this way you won't know which people are actually authenticated, this is what (in our case) the server part keeps track of. 

If you need some more info around authentication token, checkout the twilio documentation as well:

https://www.twilio.com/docs/api/rest/access-tokens

**Comment by ananth10** [comment]
@FranziscaZarrai  feeling little dizziness :( . please tell me what is the best practises ? Should i generate JwtToken pro-grammatically or i should use this  https://github.com/coresystemsFSM/web-twilio-sparky?

**Comment by FranziscaZarrai** [comment]
@ananth10 Well basically the project you linked does generate JWT tokens programmtically :) - but on the server-side, not mobile. I'd definitely recommend going with a server that generates the token. You can use  https://github.com/coresystemsFSM/web-twilio-sparky but you can also roll your own, in a different programming language. Whatever works best for you.

**Comment by FranziscaZarrai** [comment]
@ananth10 Apologies, but I do not provide personal support :) - if you have additional questions that are related to the project's here you're welcome to post them as issues. However please bear in mind, that we can not provide detailed instructions on how to implement a particular requirement.

**Comment by ananth10** [comment]
@FranziscaZarrai . Oh ..Thats okay. First let me get clear thing about generating jwtToken.  in this project

https://github.com/twilio/video-quickstart-android . i have created token and identity from Testingtool in twillio console . but this is good for to test sample app . but in real time people would install my app so i need to generate token and identity dynamically through code. as per your suggestion i had a look on this 

https://www.twilio.com/docs/api/rest/access-tokens . Here used java code to generate token.  but when i tried to use that code  i was facing import issue for "VideoGrant" . is there any other library to import  "VideoGrant"?

Is there a way to generate token from client app(https://github.com/twilio/video-quickstart-android). ??

**Comment by FranziscaZarrai** [comment]
@ananth10 

The credentials required to generate Tokens server-side are listed here (README.md file):
https://github.com/coresystemsFSM/web-twilio-sparky
It also links to where you can get those from within your Twilio Account.

Regardless of where you generate your token you'll need above credentials, i.e.:

- Twilio Account SID - Your main Twilio account identifier - find it on your dashboard.
- Twilio Video Configuration SID - Adds video capability to the access token - generate one here
- API Key	Used to authenticate - generate one with your Twilio Account (on their website)
- API Secret - Used to authenticate - just like the above

Now if you have those four things. Then Twilio offers a few server-side SDKs for Token generation for multiple languages, such as Java:

https://www.twilio.com/docs/libraries/java

The above link shows how to import their library (this is where you get the VideoGrant class from) either with Maven or as a downloadable jar file: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.twilio.sdk%22%20AND%20a%3A%22twilio%22

If you really insist on generating your codes client side (I am not sure if this will work and it's definitely not a good idea), then maybe adding above library to your android project as a jar file would work.

As for your last question: Afaik there is no way to generate a token from within the https://github.com/twilio/video-quickstart-android project as-is, since the library it uses is not the one for generating token. Instead they use the Android SDK from Twilio meant for client-side use in order to use the video feature: https://github.com/twilio/video-quickstart-android/blob/master/quickstart/build.gradle (in the dependencies section you can see that they're adding the android twilio SDK as a dependency)

**Comment by ananth10** [comment]
@FranziscaZarrai So the way is using java library . but you mentioned **If you really insist on generating your codes client side (I am not sure if this will work and it's definitely not a good idea), then maybe adding above library to your android project as a jar file would work.**  . **This is not a good idea** so  i  should i use https://github.com/coresystemsFSM/web-twilio-sparky to generate token. as of now i understood twillio sparky will help to generate token. but i am little confused about setup sparky server. actually people will install my app . and i can integrate twillio client sdk with my app.  should i integrate https://github.com/coresystemsFSM/web-twilio-sparky with my app? (to generate token) . if it is then how can i add spraky with my app.?

**Comment by FranziscaZarrai** [comment]
@ananth10 I think it would make more sense, if you'd posted that last comment on the github repo of the server you're referring too ;) . 

So, how to setup and install sparky is explained here: 
https://github.com/coresystemsFSM/web-twilio-sparky

If you simply follow above instructions and thus start sparky on your local machine it'll run at localhost:4567 > you'll see the web interface (which isn't authenticating right now, so you can't actually call from there). 

Now in order to have the mobile app talk to sparky you'll have to make sparky publicly available and add that URL on the mobile client (sparkyUrl field - more details on the mobile project's README.md).

**Comment by ananth10** [comment]
@FranziscaZarrai Thank you :) . i have setup local server :)
